/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author USRVI-LC2
 */
public class Frm_menuPpal extends javax.swing.JFrame {

    /**
     * Creates new form Frm_menuPpal
     */
    public Frm_menuPpal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_ingresarLibro = new javax.swing.JMenuItem();
        jmi_eliminarLibro = new javax.swing.JMenuItem();
        jmi_actualizarLibro = new javax.swing.JMenuItem();
        jmi_listarLibros = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmi_salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        jMenu1.setText("Opciones");

        jmi_ingresarLibro.setText("Ingresar Libro");
        jmi_ingresarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ingresarLibroActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_ingresarLibro);

        jmi_eliminarLibro.setText("Eliminar Libro");
        jmi_eliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarLibroActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_eliminarLibro);

        jmi_actualizarLibro.setText("Actualizar Libro");
        jmi_actualizarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_actualizarLibroActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_actualizarLibro);

        jmi_listarLibros.setText("Listar Libros");
        jmi_listarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_listarLibrosActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_listarLibros);
        jMenu1.add(jSeparator1);

        jmi_salir.setText("Salir");
        jmi_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_salirActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_ingresarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ingresarLibroActionPerformed
        Frm_IngresarLibro ingresar = new Frm_IngresarLibro();
        ingresar.setVisible(true);
    }//GEN-LAST:event_jmi_ingresarLibroActionPerformed

    private void jmi_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmi_salirActionPerformed

    private void jmi_listarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_listarLibrosActionPerformed
       Frm_listarLibros listar = new Frm_listarLibros();
       listar.setVisible(true);
    }//GEN-LAST:event_jmi_listarLibrosActionPerformed

    private void jmi_eliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarLibroActionPerformed
        Frm_eliminar eliminar = new Frm_eliminar();
        eliminar.setVisible(true);
    }//GEN-LAST:event_jmi_eliminarLibroActionPerformed

    private void jmi_actualizarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_actualizarLibroActionPerformed
       Frm_Actualizar actualizar = new Frm_Actualizar();
       actualizar.setVisible(true);
    }//GEN-LAST:event_jmi_actualizarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_menuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_menuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_menuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_menuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_menuPpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem jmi_actualizarLibro;
    private javax.swing.JMenuItem jmi_eliminarLibro;
    private javax.swing.JMenuItem jmi_ingresarLibro;
    private javax.swing.JMenuItem jmi_listarLibros;
    private javax.swing.JMenuItem jmi_salir;
    // End of variables declaration//GEN-END:variables
}
